@echo off
:: Test: test_MainMenu_display.cmd
:: Goal: Verify that the main menu log file contains the anchor text.

setlocal

set "LOG_FILE=%~dp0..\reports\main_script.log"
set "ANCHOR_TEXT=Install All In One Online"

:: This test no longer runs the script. It only checks the log file
:: which is generated by the workflow file itself.

if not exist "%LOG_FILE%" (
    echo [FAILURE] Log file not found: %LOG_FILE%
    exit /b 1
)

findstr /C:"%ANCHOR_TEXT%" "%LOG_FILE%" > nul

if %errorlevel% equ 0 (
    echo [SUCCESS] Main menu display test passed. Anchor text found in log.
    endlocal
    exit /b 0
) else (
    echo [FAILURE] Main menu display test failed. Anchor text NOT found in log.
    endlocal
    exit /b 1
)

