
name: Run CMD Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create test reports directory
      run: mkdir .\tests\reports
      shell: cmd

    - name: (DEBUG) List all files
      run: dir /s
      shell: cmd

    - name: Generate script output log
      shell: cmd
      run: |
        echo 7 > "%GITHUB_WORKSPACE%\tests\input.txt"
        "%GITHUB_WORKSPACE%\Helpdesk-Tools.cmd" < "%GITHUB_WORKSPACE%\tests\input.txt" > "%GITHUB_WORKSPACE%\tests\reports\main_script.log" 2>&1
        echo "Script output log generated."

    - name: Run test suite to verify logs
      run: .\tests\test_runner.cmd
      shell: cmd
