
name: Run CMD Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create test reports directory
      run: mkdir tests\reports
      shell: cmd

    - name: Generate MainMenu output log
      shell: cmd
      run: .\Helpdesk-Tools.cmd /test > .\tests\reports\main_menu.log 2>&1

    - name: Generate InstallMenu output log
      shell: cmd
      run: echo 1 | .\Helpdesk-Tools.cmd /test > .\tests\reports\install_menu.log 2>&1

    - name: Run test suite to verify logs
      run: .\tests\test_runner.cmd
      shell: cmd
