name: Run CMD Test Suite

on:
  push:
    branches:
      - 'refactor/**' # Run on pushes to any branch starting with 'refactor/'
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: windows-latest
    timeout-minutes: 2

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run Unit Test Suite
      run: tests\test_runner.cmd unit
      shell: cmd

  integration-tests:
    runs-on: windows-latest
    timeout-minutes: 2

    steps:
    - name: Check out repository
      uses: actions:checkout@v3

    - name: Run Integration Test Suite
      run: tests\test_runner.cmd integration
      shell: cmd
