name: Run CMD Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - main

jobs:
  test-main-menu:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run MainMenu Test
        shell: cmd
        run: |
          mkdir .\tests\reports
          .\Helpdesk-Tools.cmd /test:MainMenu > .\tests\reports\main_menu.log 2>&1
          .\tests\test_runner.cmd

  test-install-menu:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run InstallMenu Test
        shell: cmd
        run: |
          mkdir .\tests\reports
          .\Helpdesk-Tools.cmd /test:InstallMenu > .\tests\reports\install_menu.log 2>&1
          .\tests\test_runner.cmd

  test-install-aio:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run InstallAio Test
        shell: cmd
        run: |
          mkdir .\tests\reports
          .\Helpdesk-Tools.cmd /test:installAio > .\tests\reports\install_aio.log 2>&1
          .\tests\test_runner.cmd

  test-install-aio-fresh:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run InstallAioFresh Test
        shell: cmd
        run: |
          mkdir .\tests\reports
          .\Helpdesk-Tools.cmd /test:installAioFresh > .\tests\reports\install_aio_fresh.log 2>&1
          .\tests\test_runner.cmd

  test-office-windows-menu:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OfficeWindowsMenu Test
        shell: cmd
        run: |
          mkdir .\tests\reports
          .\Helpdesk-Tools.cmd /test:office-windows > .\tests\reports\office_windows_menu.log 2>&1
          .\tests\test_runner.cmd