name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Static checks
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          $ws = "$env:GITHUB_WORKSPACE"
          $script = Join-Path $ws 'scripts\test.ps1'
          if (!(Test-Path $script)) { Write-Error "Missing script: $script"; exit 1 }
          & $script -Stage static -Offline

  smoke:
    runs-on: windows-latest
    needs: static
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup shims
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          $ws = "$env:GITHUB_WORKSPACE"
          $shim = Join-Path $ws 'scripts\setup-shims.ps1'
          if (!(Test-Path $shim)) { Write-Error "Missing script: $shim"; exit 1 }
          & $shim
      - name: Smoke test (dry-run)
        shell: pwsh
        env:
          SAFE_MODE: '1'
          DRY_RUN: '1'
          CI: '1'
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          $ws = "$env:GITHUB_WORKSPACE"
          $script = Join-Path $ws 'scripts\test.ps1'
          if (!(Test-Path $script)) { Write-Error "Missing script: $script"; exit 1 }
          & $script -Stage smoke -Offline

  unattend:
    runs-on: windows-latest
    needs: static
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate unattend XML
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          $ws = "$env:GITHUB_WORKSPACE"
          $script = Join-Path $ws 'scripts\test.ps1'
          if (!(Test-Path $script)) { Write-Error "Missing script: $script"; exit 1 }
          & $script -Stage unattend -Offline
