name: Run CMD Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - main

jobs:
  run-dynamic-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - test_name: MainMenu
            expected_text: "Main Menu"
          - test_name: InstallMenu
            expected_text: "Install All In One Online"
          - test_name: installAio
            expected_text: "Install All in One"
          - test_name: installAioFresh
            expected_text: "Install All in One from fresh Windows without Office"
          - test_name: testActiveLicenses
            expected_text: "Active Licenses Menu"
          - test_name: testUtilitiesMenu
            expected_text: "Utilities Main Menu"
          - test_name: testOfficeWindowsMenu
            expected_text: "Windows Office Main Menu"
          - test_name: testPackageManagementMenu
            expected_text: "Package Management Software Main Menu"
          - test_name: testUpdateCMD
            expected_text: "File has been updated"
          - test_name: testInstallOfficeMenu
            expected_text: "Install Office Online"

    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ matrix.test_name }} Test
        shell: cmd
        run: |
          if not exist .\tests\reports mkdir .\tests\reports
          .\Helpdesk-Tools.cmd /test:${{ matrix.test_name }} > .\tests\reports\${{ matrix.test_name }}.log 2>&1
          call .\tests\test_runner.cmd .\tests\reports\${{ matrix.test_name }}.log "${{ matrix.expected_text }}"
