name: Run CMD Tests

on:
  # Run when pushing to feature, fix, or refactor branches
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
  # Run when a Pull Request is opened against the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run test suite
      run: .\tests\test_runner.cmd

    - name: Check test results
      run: |
        $result = Get-Content .\tests\reports\test_result.txt
        if ($result -ne "0") {
          echo "Tests failed with result code: $result"
          exit 1
        }
        echo "All tests passed with result code: $result"