name: Run CMD Tests

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate script output log
      run: |
        echo 7 | .\Helpdesk-Tools.cmd > .\tests\reports\main_script.log 2>&1
        echo "Script output log generated."

    - name: Run test suite
      run: .\tests\test_runner.cmd